import Head from 'next/head'
import { Header } from '../components/Header'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rest Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="shadow-md bg-white">
        <Header />
      </header>
      <main className="">
        <Main />
      </main>
    </div>
  )
}
